# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CatalystX Validator
email: contact@s3rdv.com
description: >-
  Professional Solana validator operated by S3RDV LLC, focused on network stability, security, and integrity.
  A Marinade Select program member delivering institutional-grade validation services.
baseurl: ""
url: "https://catalystxsol.com"
twitter_username: CatalystX_SOL
github_username: T3chie-404

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - AI_BOT_LOG.md

# Custom settings
show_posts: false
author: CatalystX Validator
logo: /assets/images/logo.png

# Social links
social:
  name: CatalystX Validator
  links:
    - https://twitter.com/CatalystX_SOL
    - https://github.com/T3chie-404

# Validator information
validator_info:
  vote_account: ErvMUdtMC7AX55zKdYSyy4DnWNCrTsWn5GwprSG7ocnx
  commission: 5%
  uptime: 99.99%
  performance_score: 100%
  locations:
    primary: "Amsterdam, Netherlands"
    backup: "Madrid, Spain"
  hardware:
    cpu: "AMD EPYC 7543 32-Core Processor"
    ram: "128GB ECC DDR4"
    storage: "2TB NVMe SSD"
    bandwidth: "1Gbps Dedicated"

# SEO settings
twitter:
  username: CatalystX_SOL
  card: summary

# Navigation
header_pages:
  - about.md
  - services.md
  - statistics.md
  - contact.md
